# Generated by Django 3.1.6 on 2021-02-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divorce', '0003_auto_20210217_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorce',
            name='Date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='Highest_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='Maritial_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='Nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='State_issued_divorce_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
